sudo: false
language: node_js
cache:
  directories:
  - node_modules
  - jspm_packages
notifications:
  email: false
node_js:
  - '4.2'
before_script:
  - npm prune
  - npm dedupe
before_install:
  - npm run setup
